const pdfMake = require('pdfmake/build/pdfmake.js');
import { Injectable } from '@angular/core';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
import { EmailService } from './email-service';
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;


@Injectable({
  providedIn: 'root'
})
export class PdfService {

  constructor(private emailService: EmailService) {
  }

  public generateAndDownloadPdf(title: string, content: string): void {
    let documentDefinition = this.getDocumentation(title, content);
    pdfMake.createPdf(documentDefinition).download('CobotReport.pdf');
  }

  public mailDocumentation(emailAddress: string, reportBody: string) {
    const subject = 'Cobot Report';
    const body = 'Please find the attached file. \n' + reportBody;
    const mailtoLink = 'mailto:' + emailAddress + '?subject=' + subject + '&body=' + body;
    window.open(mailtoLink);
  }

  getDocumentation(title: string, content: string) {
    const documentDefinition = {
      content: [
        {
          text: 'COBOT REPORT',
          fontSize: 20,
          alignment: 'center',
          color: '#4A00E0',
          bold: true,
          margin: [0, 0, 0, 20]
        },
        {
          text: title,
          fontSize: 18,
          alignment: 'center',
          color: '#F37335',
          bold: true,
          margin: [0, 0, 0, 20]
        },
        {
          text: content,
          fontSize: 12,
          alignment: 'justify',
          margin: [0, 0, 0, 20]
        },
        {
          text: 'The report is generated by cobot AI, developed as a part of Epsilon Hackathon 23',
          fontSize: 10,
          alignment: 'right',
          bold: true
        }
      ]
    };
    return documentDefinition;
  }


}